### ISSUE TITLE
Mehrere Inverter

### ISSUE THREAD

**Issue by VOPAtec** [Telekatz/venus.dbus-hoymiles#1]
Hallo Telekatz,
das ist wirklich ein super Ansatz, die Inverter direkt in Venus zu integieren. Meine Frage ist, wie das ganze mit mehreren , z.B. 3 Stück HM1500 an einer DTU, aussehen würde. Würde dies schon funktionieren?
Vielen Dank und Grüße
Volker

**Comment by Telekatz** [comment]
Nein, mehr als ein Inverter wird aktuell nicht unterstützt.

**Comment by VOPAtec** [comment]
Schade, besteht denn die Chance, dass es irgendwann kommt? 
Ich finde es bis jetzt die schönste Lösung, da die Konfiguration über die Console vom Cerbo gemacht wird.
Ich versuche es gerade mit [dbus-mqtt-devices] allerdings scheitere ich an der Configuration von Tasmota nach dem Registration Protocol.
Aktuell habe ich nur einen HM1200 laufen. Würde das "out of the box" funktionieren?
Vielen Dank und Grüße

**Comment by Telekatz** [comment]
Wird vielleicht noch kommen. Hab selber aber auch nicht mehrere Inverter, um das testen zu können.
Ein HM1200 sollte funktionieren.
