### ISSUE TITLE
Startup limit min/max

### ISSUE THREAD

**Issue by TTr0n** [Telekatz/venus.dbus-hoymiles#11]
Hello Telekatz,

thx for this module!
Actually i am testing with this and wondering how to configure the Startup limit min and max.  and the feed-in limit mode.

My system looks like yours, but containes an additionally pv generater, which Venus didnt know (SMA SB5000TL-20) and the total grid power is <0 with enough sunshine. Maybe thats my problem !?

Startup limit = off -> feed-in mode grid and load seems ok , but what does managed by VenusOs mean? 
If i choose it and battery is full loaded, the mppt runs down and no feed-in is generated. If i choose maximum power, the inverter feeds with selected power, but all the time and is using the battery, if there isnt enough power from mppt. 
Is there an option for feed-in only the overhead power with selected startup min/max ? And if there isnt enough power to reduce gridpower to configured value, then battery will be used ?

Or any other idea? Maybe i am confused with all these options -.-

Greetings

**Comment by Telekatz** [comment]
The feed-in limit mode `Venus OS` is similar to the mode `Grid Target` but controlled by Venus OS and not by the script.

To feed in when the battery is full you can activate `DC-coupled PV - feed in excess`. This is a setting in the `Grid feed-in` sub menu inside the `ESS` menu.

**Comment by TTr0n** [comment]
Ok, done .. but nothing changed. 
What are the suggested values for loading voltage in DVCC options, if the Pylontech is a 48V LiFePO4 US5000?
BMS shows 53,2V but most threads in forum say use 52V in DVCC, Victron says there is an internal override and caped on 52,4V .
Any Ideas?

Evtl. is eine Unterhaltung auf Deutsch sinnvoller, falls möglich? ;-)

**Comment by Telekatz** [comment]
Die Übeschusseinspeisung wird nur aktiv bei einem SOC von 100%. Und es muss natürlich ein Überschuss vorhanden sein. 

An den DVCC Einstellungen habe ich nichts geändert. Venus OS begrenzt die Spannung auf 52,4V.

**Comment by Head** [comment]
DVCC ist bei mir auch "Forced on" und bei 52,4V ist Schluss. Das macht Pylontech mit dem Venus OS unter sich aus.

Meine Beobachtung mit den Modi hier ist:

"Base Load" macht eine gute Arbeit und speist keinen Akkustrom ein, wenn man mal am Herd ist.

Für Grid Target oder Venus OS ist diese "überall 5s"-Regelung eigentlich zu lahm, auch ärgert mich mein Hoymiles, weil er zwischen 200 und 300W anfängt um 100W nach unten zu schwanken. (Bei z.B. 230W eingestellt liefert er nervöse 100-220W, Venus denkt aber er macht 230W und dreht 100W hoch, dann macht er 330W und speist ein, dann dreht Venus wieder runter etc etc...) Sieht dann so aus:
![image](https://github.com/Telekatz/venus.dbus-hoymiles/assets/51700/b22e2185-186d-4ea3-b6a6-c2758a94ff6e)

Leider speist "Base Load" nichts ein. Die beiden anderen Einstellungen erst ab 100% SoC. Hier ist auch etwas doof, dass vor 100% mein MPPT nach und nach abregelt. (Das Haus wird weiter bedient.) Hier könnte man theoretisch schon vorher mit der Einspeisung anfangen. Im Bild hier sogar 2 mal:
![image](https://github.com/Telekatz/venus.dbus-hoymiles/assets/51700/2087418a-46bc-4d2a-bcab-2015c859a965)

Startup Limit sorgt "irgendwie" dafür, dass am Morgen, bei aufgehender Sonne, kein Akku verbraucht wird und nur der Überschuss eingespeist wird. Hierzu habe ich Min 50W, Max 550W eingestellt. Das läuft dann eigentlich ganz gut (, wenn ich nicht wegen Tibber am Min-SoC rumspielen würde...)

Aktuell bin ich am überlegen, wie man die Tibber-Steuerung besser umsetzen könnte und auch den Überschuss bei prognosebasiert vollem Akku schon am Morgen einspeisen könnte, wie es SMA wohl macht. Aber das ist ein Thema für einen anderen Issue/Thread.

**Comment by TTr0n** [comment]
Kurze Rückmeldung: Mit der Option DC Überschusseinspeisung = an , schien es bis gerade eben zu klappen.
Allerdings sind jetzt alle 3 MPPTs runtergeregelt. Einer liefert ca. 50W und die anderen beiden 1-4W , SoC ist allerdings auch gerade bei 99%, während die Spannung bei 52,37V ist.
Vorher bei SoC 100%, war die Spannung allerdings noch bei 51,7V ... verstehe ich irgendwie nicht so ganz -.-

**Comment by Head** [comment]
Ja, das ist ja das was ich meinte. Unter 100% wird nichts eingespeist. Siehe auch im Code hier: https://github.com/Telekatz/venus.dbus-hoymiles/blob/main/HMpvinverter.py#L1085
Deswegen frage ich mich ja auch, was denn passiert wenn man sagen würde:
SoC > 90% ? dann Wechselrichter = max(Grid, PV)

**Comment by Telekatz** [comment]
Dass erst ab 100 % SOC der Überschuss eingespeist wird liegt daran, dass es einfacher umzusetzen war. Aber ich versuche es noch so zu ändern, dass auch schon eingespeist wird, sobald der MPPT limitiert wird.

**Comment by TTr0n** [comment]
Das wäre toll :-) 👍

**Comment by Head** [comment]
Habe grad heute den Akku mal wieder auf 100% geladen, dabei den Welchelrichter auf 100W begrenzt und etwas die Float Lampe beobachtet - die geht hier nicht an... er bleibt auf absorption sobald der Pylontech auf 52V ist...
Auf jeden Fall habe ich dabei auch gefunden, dass es com.victronenergy.solarcharger.ttyUSB0.**MppOperationMode** gibt, der auf 1 ist, sobald der MPPT limitiert läuft. Eigentlich müsste das ja ausreichen als Indiz den Inverter hoch zu regeln. Dann noch Dc/0/Power beobachten und so auspendeln, dass der auf 0 und der MppOperationMode auf 2 sind.

**Comment by Telekatz** [comment]
Ich habe zum testen den Branch [feedInExcess](https://github.com/Telekatz/venus.dbus-hoymiles/tree/feedInExcess) erstellt. 

Die Überschusseinspeisung ist jetzt so abgeändert, dass anhand der Limitierung des MPPT der Inverter hoch geregelt wird. Und feed in excess funktioniert jetzt auch mit dem `Base Load` Limit Mode.

**Comment by Head** [comment]
Sehr cool, schau ich mir... in einer Woche hoffentlich mal an... Bei dem Wetter die nächste Woche habe ich eher keinen Überschuss, bekomme aber noch ne Handvoll Panels dazu, dann wird das wahrscheinlich täglich genutzt werden :) Ich werde berichten.

**Comment by TTr0n** [comment]
Vielen Dank 👍 
Ich habe gerade die HMpvinverter.py ersetzt.
Mal schauen wie es morgen aussieht bezgl. Sonnenschein und Verhalten bei der Überschusseinspeisung.

**Comment by TTr0n** [comment]
Das Wetter ist aktuell leider zu schlecht, um aussagekräftige Ergebnisse zu bekommen.
Was mir allerdings aufgefallen ist, ist weiterhin eine Art Abregelung der MPPTs.
Ich habe 3 Stk. an dem Venus ( 2x Süd, 1x West ) und die beiden mit Südausrichtung liefern nur unregelmäßig die gleiche Leistung. 
Aktuell habe ich bei dem HM die FeedIn Option "VenusOs" ausgewählt. Ich werde mal auf "GridTarget" umstellen und schauen ob sich das Verhalten ändert.
Was genau ist denn im Detail der Unterschied zw. den beiden Optionen?

**Comment by Telekatz** [comment]
Der Unterschied zwischen `Grid Target` und `Venus OS` ist, dass der eine im Script implementiert ist, der andere der von Venus OS ist. `Venus OS` regelt häufiger nach, `Grid Target` nur beim unter oder überschreiten der selbst definierbaren Grenzwerte. Aber einen Unterschied bei MPPT Limitierung wir es da nicht geben.

**Comment by TTr0n** [comment]
Ok, wenn es daran nicht liegen kann, woran dann?
Was kann ich an Daten liefern, um das Problem einzugrenzen?
Hier sieht man die Schwankungen der MPPTs und auch die des HM. Es war zum Teil so, das kurz vor erreichen der eingestellten Ziel Batteriespannung, der HM auf 900w (eingestellte Max Grenze) hoch gefahren wurde, nur um kurz danach die Batterie wieder zu laden ...
![Screenshot_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/75184361/2d129459-2daa-4147-b49a-16ac97a5b73c)
![Screenshot_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/75184361/7ee499b7-564d-45a4-937d-f7ed6768d8e0)

**Comment by Telekatz** [comment]
Da fängt die Regelung an zu schwingen. Teste mal die neue Version vom feedInExcess Branch. Ich hab die Regelung etwas träger gemacht.

**Comment by TTr0n** [comment]
Danke, wird gemacht.
Melde mich wieder :-)

**Comment by TTr0n** [comment]
Leider ist das Wetter aktuell nicht stabil genug, aber heute gegen Abend war der SOC bei 96% und die Batteriespannung wurde mit 51,7x V angezeigt. Kurz darauf wurde dann für einen kurzen Moment über den HM voll eingespeist, also nicht der Überschuss, sondern das Delta zum eingestellten Maxwert aus der Batterie gezogen! 
Die Grundlast im Netz lag bei ca. 450W und die 2. PV hat zu dem Zeitpunkt ca. 2500W eingespeist. Somit lag der Gridwert deutlich im Minus und von der Last im Haus her, gab es keinen Grund mit den eingestellten Max 900W einzuspeisen. 
Das ging dann ein paar mal hin und her ... Ist das von der Funktionalität her so gewollt? Nach meinem Verständnis, dürfte der HM doch nur mit der Leistung angesteuert werden, die nicht in die Batterie geht!?

**Comment by Telekatz** [comment]
Die Leistung, die nicht in die Batterie geht, ist nicht bekannt. Ob Überschuss vorhanden ist sieht man nur am Wert von `mppOperationMode` des Ladereglers. Ist dieser Wert bei mindestens einem Laderegler 1 wird die Leistung des Inverters ausgehend vom momentanen Wert schrittweise erhöht, bis entweder die Maximalleistung des Inverters erreicht ist oder bis der Laderegler nicht mehr gedrosselt wird (mppOperationMode = 2). Dann geht die Leistung des Inverters schrittweise runter bis wieder Überschuss vorhanden ist.

Könntest  du bitte zusätzlich zur PV Leistung und Inverterleistung die Werte /hm/0/Debug0 und /hm/0/Debug1 über MQTT mitloggen? Damit könnte man sehen, wie die Überschusseinspeisung bei dir arbeitet.

**Comment by TTr0n** [comment]
Hmm ... also der Pylontech liefert doch die Info, mit wieviel Watt die Batterie geladen wird und von den MPPTs kommt die Info wieviel geliefert wird, das Delta davon sollte doch der Überschuss sein !? Ist wahrscheinlich zu einfach gedacht, aber so hatte ich mir das bisher vorgestellt ;-)
Ich habe aktuell die Verbindung zum VenusOs per Modbus und lese über die Modbus Register die Werte aus. Wie/wo komme ich denn an die Debug0 und Debug1 Werte? Von der OpenDTU her sehe ich die nicht.

**Comment by TTr0n** [comment]
Ich habe in der config.ini mal den Loglevel auf Debug gestellt und das Log durchgesehen, es gibt da zumindest einen Error:

`2023-07-30 18:42:14,894 root ERROR Error at _on_MQTT_message
Traceback (most recent call last):
  File "/data/dbus-hoymiles/HMpvinverter.py", line 639, in _on_MQTT_message
    if k in {'ch0/P_AC','0/power'} and self._dbusservice['/RunState'] >= 1:
AttributeError: 'DbusHmInverterService' object has no attribute '_dbusservice'`

Wie ich an die beiden Debug Werte per MQTT komme, kann ich mir gerade nicht herleiten -.-

**Comment by Telekatz** [comment]
Da die Energie nicht verschwindet, liefert der MPPT genau so viel, wie die Batterie und Inverter abnehmen. Daraus kann man aber nicht den Überschuss berechnen, da man nicht weiß, wie viel der MPPT liefern könnte.

Um die Debug Werte zu bekommen musst du den MQTT Server in Venus OS aktivieren.

**Comment by TTr0n** [comment]
Ok, wie mache ich das? :-)
Du meinst aber nicht den NodeRed, sondern etwas anderes ?

**Comment by Telekatz** [comment]
Der MQTT Server wird in den Einstellungen unter Dienste aktiviert. Und dann musst du halt noch herausfinden, wie in deinem HA System Daten von eimem MQTT Server geholt werden.

**Comment by TTr0n** [comment]
Ja, das mit dem Abholen der Daten war klar, nur wusste ich bisher nicht, wie ich den intern MQTT "an" schalte.
Danke!

*edit*
Nachdem die Verbindung zum Venus MQTT Server da ist, dachte ich eigentlich, das Änderungen automatisch mitgeteilt werden.
Allerdings muss ich alle 30sec. einen Request schicken, damit die Werte aktualisiert werden. Gibt es keine Subscribe Möglichkeit ?

**Comment by Head** [comment]
Die (Debug) Werte kann man auch schön über SSH im dbus-spy beobachten, aber MQTT geht auch.

Ich hatte gestern 100% SoC und das Script lief noch im StartLimit Mode. Der Wechselrichter lief auf ~140W, es war sehr wechselhaft Wolkig, also immer 140W und 700W im Wechsel. Aber ich habe beobachtet wie Debug0 auf 1 war und Debug0 langsam aber stetig auf 600 hoch gekrabbelt ist. Mit den Wolken ist aber auch super mies und imho so nicht zu regeln.

**Comment by TTr0n** [comment]
Ich habe aktuell nur Datenpunkte im 10sec Abstand, da ein Subscript auf den Venus MQTT nicht funktioniert.
Das hier ist von Heute:
![Screenshot_07 08](https://github.com/Telekatz/venus.dbus-hoymiles/assets/75184361/3c29d4d3-143a-40b4-ac0e-0bad1182312f)

**Comment by Head** [comment]
Ich vermute es gibt ein Problem, wenn der Wechselrichter mehr kann, als die Sonne liefert.

Bei dem "Sägezahn" hatte ich den Wechselrichter auf 750W stehen, Akku war auf 98%, Sonne lieferte ~500W. Der MppOperation (und Debug1) gingen immer auf Abregelung, dann drehte er den Wechselrichter hoch, bis er aus der Batterie gezogen hat, dann wieder runter, wieder in die Abregelung, etc.
Habe dann den Wechselrichter auf 500W gestellt und dann lief es sauber bis der Akku auf 100% war und da läuft es jetzt auch schön.
![image](https://github.com/Telekatz/venus.dbus-hoymiles/assets/51700/c9028457-3f3c-4265-aab8-581c889f2d82)

**Comment by Telekatz** [comment]
Etwas "Sägezahn" ist ja beabsichtigt. Nur so findet man die Maximale Leistung des MPPT indem man um den Wert herumregelt. Aber das Überschwingen ist immer noch zu groß. Wenigstens ist das Wetter jetzt wieder besser zum testen.

![solar](https://github.com/Telekatz/venus.dbus-hoymiles/assets/13141642/70ed40f6-aab3-43a4-9945-67bc140ba70b)

**Comment by TTr0n** [comment]
Gibt's schon neue Erkenntnisse? Die nächsten Tage wird das Wetter ja wieder stabiler (zumindest hier in Niedersachsen).

**Comment by Telekatz** [comment]
Bin noch am testen. Gab in den letzten Tagen nicht viel Überschuss. Hab die aktuelle Version gerade hochgeladen.

**Comment by Telekatz** [comment]
Da zum testen in diesem Jahr bei mir kein Überschuss mehr zu erwarten ist, habe ich den aktuellen Stand der Überschusseinspeisung in den Main Branch übernommen und mach hier erstmal zu.

**Comment by Head** [comment]
Sollte soweit passen, ich laufe auch seit einer Weile auf dem Branch und hatte glaube 1-2 mal Überschuss, sah gut aus.
