### ISSUE TITLE
Keine Anzeige mehr nach Installation, nur noch weißer Bildschirm

### ISSUE THREAD

**Issue by gerd-git** [Telekatz/venus.dbus-hoymiles#12]
Hallo Telekatz,

nach Installation via:

```
root@raspberrypi2:~# wget https://github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/main.zip
--2023-07-12 11:32:54--  https://github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/main.zip
Resolving github.com... 140.82.121.3
Connecting to github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Telekatz/venus.dbus-hoymiles/zip/refs/heads/main [following]
--2023-07-12 11:32:55--  https://codeload.github.com/Telekatz/venus.dbus-hoymiles/zip/refs/heads/main
Resolving codeload.github.com... 140.82.121.10
Connecting to codeload.github.com|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘main.zip’

main.zip                                                        [ <=>                                                                                                                                     ] 521.02K  3.01MB/s    in 0.2s

2023-07-12 11:32:55 (3.01 MB/s) - ‘main.zip’ saved [533528]

root@raspberrypi2:~# /data/dbus-hoymiles/uninstall.sh
-sh: /data/dbus-hoymiles/uninstall.sh: No such file or directory

root@raspberrypi2:~# unzip main.zip "venus.dbus-hoymiles-main/*" -d /data
Archive:  main.zip
   creating: venus.dbus-hoymiles-main/
  inflating: venus.dbus-hoymiles-main/HMpvinverter.py
  inflating: venus.dbus-hoymiles-main/LICENSE
  inflating: venus.dbus-hoymiles-main/README.md
  inflating: venus.dbus-hoymiles-main/config.ini
   creating: venus.dbus-hoymiles-main/img/
  inflating: venus.dbus-hoymiles-main/img/inverter.png
  inflating: venus.dbus-hoymiles-main/img/main.png
  inflating: venus.dbus-hoymiles-main/img/settings.png
  inflating: venus.dbus-hoymiles-main/img/system_diagram.png
  inflating: venus.dbus-hoymiles-main/install.sh
   creating: venus.dbus-hoymiles-main/qml/
  inflating: venus.dbus-hoymiles-main/qml/MultiHm.qml
  inflating: venus.dbus-hoymiles-main/qml/OverviewGridParallel.diff
  inflating: venus.dbus-hoymiles-main/qml/PageHmSetup.qml
  inflating: venus.dbus-hoymiles-main/qml/PageMain.diff
  inflating: venus.dbus-hoymiles-main/qml/PageVebusHm.qml
  inflating: venus.dbus-hoymiles-main/qml/overview-inverter-Hm.svg
  inflating: venus.dbus-hoymiles-main/qml/overview-inverter-short-Hm.svg
  inflating: venus.dbus-hoymiles-main/restart.sh
   creating: venus.dbus-hoymiles-main/service/
  inflating: venus.dbus-hoymiles-main/service/run
  inflating: venus.dbus-hoymiles-main/uninstall.sh
root@raspberrypi2:~# mv /data/venus.dbus-hoymiles-main /data/dbus-hoymiles
root@raspberrypi2:~# chmod a+x /data/dbus-hoymiles/install.sh
root@raspberrypi2:~# /data/dbus-hoymiles/install.sh
patching file /opt/victronenergy/gui/qml/PageMain.qml
patching file /opt/victronenergy/gui/qml/OverviewGridParallel.qml
`root@raspberrypi2:~#
```

wird nichts mehr angezeigt:

![Telekatz](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/cb5b76dc-da06-4af6-9400-581909b7144a)

Auch ein 

`root@raspberrypi2:~# reboot
`
 brachte nix.

Glücklicherweise ist wieder alles ok nach zweimal uninstall.sh, jedoch gab es Fehlermeldungen:

```
root@raspberrypi2:~# /data/dbus-hoymiles/uninstall.sh
/data/dbus-hoymiles/uninstall.sh: line 8: ./restart.sh: No such file or directory
root@raspberrypi2:~# /data/dbus-hoymiles/uninstall.sh
rm: can't remove '/service/dbus-hoymiles': No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
/data/dbus-hoymiles/uninstall.sh: line 8: ./restart.sh: No such file or directory
cp: can't stat '/opt/victronenergy/gui/qml/OverviewGridParallel._qml': No such file or directory
cp: can't stat '/opt/victronenergy/gui/qml/PageMain._qml': No such file or directory
rm: can't remove '/opt/victronenergy/gui/qml/OverviewGridParallel._qml': No such file or directory
rm: can't remove '/opt/victronenergy/gui/qml/PageMain._qml': No such file or directory
rm: can't remove '/opt/victronenergy/gui/qml/MultiHm.qml': No such file or directory
rm: can't remove '/opt/victronenergy/gui/qml/PageHmSetup.qml': No such file or directory
rm: can't remove '/opt/victronenergy/gui/qml/PageVebusHm.qml': No such file or directory
rm: can't remove '/opt/victronenergy/themes/ccgx/images/overview-inverter-Hm.svg': No such file or directory
rm: can't remove '/opt/victronenergy/themes/ccgx/images/overview-inverter-short-Hm.svg': No such file or directory

```

venus os v3.00

Gruß Gerd

**Comment by Telekatz** [comment]
Im main Branch ist noch die Version für Venus OS V2.92. Für V3.00 gibt es einen eigenen Branch. Da musst du die Installationsdateien aber selber auf den Pi kopieren.

**Comment by Head** [comment]
Die im 3er Branch funktioniert auch unter v3.10~9 bei mir.
Auch bei der neuen /gui-beta/ von Venus, sieht alles korrekt aus:
![image](https://github.com/Telekatz/venus.dbus-hoymiles/assets/51700/d9e5b30d-1e02-4c55-89b1-eb53893a1293)

**Comment by gerd-git** [comment]
Sieht sehr gut aus. Danke.
Muss ich die Dateien alle einzeln laden oder gibt es auch ein main.zip? Sorry, ich kenn mich mit git nicht so gut aus.

Dann noch ne Frage bzgl. Betrieb neben einen Multiplus.:
Da der Multiplus extrem laut ist, ist meine Idee, den Multiplus Nachts auszuschalten und für die Grundlast einen HM-300 als inverter direkt an der Batterie einzuschalten. Das die beiden nicht gleichzeitig laufen können, kann ich mir vorstellen, aber eine Tag-/Nachtumschaltung sollten doch machbar sein, oder?

**Comment by Telekatz** [comment]
Das Archiv zum V3.00 Branch gibt es hier [https://github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/Venus_OS_V3.00.zip](https://github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/Venus_OS_V3.00.zip)

> Das die beiden nicht gleichzeitig laufen können, kann ich mir vorstellen, aber eine Tag-/Nachtumschaltung sollten doch machbar sein, oder?

Nein, ein gleichzeitige Installation mit einem Multiplus ist nicht möglich.

**Comment by gerd-git** [comment]
Danke.

Und schade, ich muss dann da ne andere Lösung suchen. Ich kann den HM-300 ja einfach dran klemmen, aber leder zählt das VRM den Grid-verbrauch nicht mehr, wenn der Multiplus aus ist....

**Comment by Head** [comment]
Man kann beim Multiplus die Lüfter tauschen, da gibt es auch Firmen, die das anbieten. Kenne mich da aber selbst nicht aus, habe das nur mal gesehen.
Wer hat den Multiplus denn installiert? Woher bekommt der die Grid Daten?

**Comment by gerd-git** [comment]
Ja, Lüfter schon getauscht und weich aufgehangen. Außerdem gibt es sogar schon ein Fan Upgrade Kit von Victron zur Nachrüstung, damit das Rattern der Lüfters bei geringer Umdrehung verschwindet. Der Lüfter ist aber trozdem immer noch sehr laut bei Volllast, aber das ist ja hautsächlich nur Tagsüber wenn man wach ist.
Das Hauptproblem ist Nachts, wenn alles andere ruhig ist und man schlafen will. Der Multiplus brummt mit 60dB sehr laut auch bei geringer Last. Trotz Lärmschutzdübel und Terassenpads ist er deutlich durch die geschlossene Tür zu hören. Ein Victron Garantieantrag wurde von mir auch schon gestellt, wurde aber abgelehnt.

Ansich ist der Multiplus ja DAS Gerät für DIY wenn man Nulleinspeisung bzw. Überschutzeinspeisung machen will. Aber für Nachts brauche ich eine Alternative. Zumindest für die Grundlast ist ein HM-300 ideal. Funktioniert auch, wird aber nicht im VRM berücksichtigt, da im VRM die Netzlast nicht mehr gezählt wird sobald der Multiplus aus ist. [Siehe hier](https://community.victronenergy.com/questions/218196/vrm-zeigt-na-beim-netz-wenn-multiplus-aus-ist.html).

Schade, dass eine "ein gleichzeitige Installation mit einem Multiplus" nicht klappt.
Könnte sich das in Zukunft ändern?

GridDaten werden bei mir via EM24 gemessen.

**Comment by gerd-git** [comment]
> Das Archiv zum V3.00 Branch gibt es hier https://github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/Venus_OS_V3.00.zip
> 

Ich wollte das probieren, aber leider wieder nur weißer Bildschirm:

```
root@raspberrypi2:~# wget github.com/telekatz/venus.dbus-hoymiles/archive/refs/heads/Venus_OS_V3.00.zip
root@raspberrypi2:~# unzip Venus_OS_V3.00.zip "venus.dbus-hoymiles-Venus_OS_V3.00/*" -d /data
root@raspberrypi2:~# mv /data/venus.dbus-hoymiles-Venus_OS_V3.00/ /data/dbus-hoymiles
root@raspberrypi2:~# chmod a+x /data/dbus-hoymiles/install.sh
root@raspberrypi2:~# /data/dbus-hoymiles/install.sh
root@raspberrypi2:~# /reboot 
```
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/dc4c5df1-463e-42f0-a408-d9fd6560110a)

Interessant aber im VRM:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/84f2df63-8b28-4970-97e8-8d6a1bf9a7c1)

Uninstall findet restart nicht:
```
root@raspberrypi2:~# /data/dbus-hoymiles/uninstall.sh
/data/dbus-hoymiles/uninstall.sh: line 8: ./restart.sh: No such file or directory
root@raspberrypi2:~#
```
Nach reboot aber wieder alles beim alten...
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/dd375196-6964-4719-95c6-9cbc30c3ac96)

**Comment by Telekatz** [comment]
Hast du immer noch den Multiplus in deinem Venus OS?

**Comment by gerd-git** [comment]
Ich hab den ausgeschaltet. Dann ein Reboot. Danach sollte er doch weg sein....

**Comment by Telekatz** [comment]
Hast du nach dem Reboot kontrolliert, ob er auch wirklich nicht mehr in der Geräteliste war?

**Comment by gerd-git** [comment]
Ich hab den jetzt auch vom VE.Bus Adapter getrennt. Ich probiere nochmal....

**Comment by gerd-git** [comment]
Jetzt sieht es anders aus:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/f484086c-8066-4e45-ad99-754a245609a5)
HM-600 wird erkannt, habe ihn gerade mal erst konfiguriert.
HM-300 fehlt noch:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/8d803ec7-3f6e-4cf4-98e1-b0d8efd3703d)

**Comment by Telekatz** [comment]
Weitere Inverter müssen erst in der config.ini aktiviert werden.

**Comment by gerd-git** [comment]
Nach reboot wird kein Inverter mehr angezeigt.

Dann Änderung von config.ini
```
[DEFAULT]
#Possible Options for Log Level: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
Logging=INFO

[Inverter1]
Deviceinstance=51

 Uncomment for additional devices
 [Inverter2]
 Deviceinstance=52

# [Inverter3]
# Deviceinstance=54
```
install nochmal aufgerufen (oder kann ich den service irgendwie anders starten?)
jetzt keine Inverter mehr da:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/e43d1269-98d8-4179-8624-cfe2b60e1cda)
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/9e652603-4e28-4cf0-b549-940b7b4ca93d)

Änderung von config.ini rückgängig gemacht:
install.sh aufgerufen, KEIN reboot
jetzt:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/1cc1ed84-950d-4fca-8b29-a4d2d9dd5d7f)
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/dc3d72e5-a8ab-4402-9cf8-1320cf8e8d96)


HM-300 fehlt.

**Comment by gerd-git** [comment]
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/b87c0c68-746c-4194-b6eb-250e9caaa1b7)

**Comment by Telekatz** [comment]
Probier's mal so:

```
[DEFAULT]
#Possible Options for Log Level: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
Logging=INFO

[Inverter1]
Deviceinstance=51

#Uncomment for additional devices
[Inverter2]
Deviceinstance=52

# [Inverter3]
# Deviceinstance=54
```

**Comment by gerd-git** [comment]
Klar hatte Tomaten auf den Augen...

```
root@raspberrypi2:~# cat /data/dbus-hoymiles/config.ini
[DEFAULT]
#Possible Options for Log Level: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
Logging=INFO

[Inverter1]
Deviceinstance=51

# Uncomment for additional devices
[Inverter2]
Deviceinstance=52

# [Inverter3]
# Deviceinstance=54
root@raspberrypi2:~# /data/dbus-hoymiles/install.sh
ln: /service/dbus-hoymiles/service: File exists
patching file /opt/victronenergy/gui/qml/PageMain.qml
patching file /opt/victronenergy/gui/qml/OverviewGridParallel.qml
root@raspberrypi2:~#

```

Trotzdem feht der HM-300 immer noch:

![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/9c20474f-2a41-4a06-8aa5-cfc7e6afe134)

**Comment by Telekatz** [comment]
Reboot gemacht?

**Comment by gerd-git** [comment]
Danke, das sieht gut aus:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/2f27371b-1a28-439f-90cf-7c7345584f9f)

Jetzt noch Überschusseinspeisung konfigurieren.... Tipp?

**Comment by Telekatz** [comment]
Einfach mal die Einstellungen ausprobieren. 

Du solltest aber auch darauf achten, nicht schneller zu regeln, als die Leistung von den Invertern aktualisiert wird. Wenn beide Inverter über die selbe DTU gesteuert werden verdoppelt sich die Zeit, in der die Aktualisierung erfolgt. Für eine schnellere Regelung würde ich ein externes Powermeter für die Inverter empfehlen.

**Comment by gerd-git** [comment]
Ich probiere schon rum.

Es gibt drei Varianten: Grid Target, Base Load, Venus OS. 
Problem bei allen Varianten: Es wird auf 50W statt auf 0W geregelt. 
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/13152951-c102-463f-af59-ec3dda39b413)
Setze ich den Sollwert auf -50W passt es:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/03398b3f-4ac2-443a-b9b4-08a53609582c)
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/a21a0a39-5a67-46fd-b696-deff6e367d6c)

Als wenn einer sich verrechnet....

**Comment by gerd-git** [comment]
Der HM-600 ändert sein Limit, der HM-300 bleibt aber auf 5% festgenagelt.
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/47084f73-aa89-4dbe-a542-c13814eabfe9)
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/4dcce527-7039-4fd6-96fe-92bb8e908cef)

**Comment by Telekatz** [comment]
Dass der HM-300 nicht regelt ist so beabsichtigt. Es wird  Primär mit dem ersten Inverter die Last ausgeregelt. Die weiteren Inverter werden erst dann nach geregelt, wenn mit dem ersten Inverter die Last nicht eingestellt werden kann.

Hast du in deinem System weitere AC gekoppelte Inverter?

**Comment by gerd-git** [comment]
Nein. Keine weiteren AC-Inverter. Und der Multiplus ist immer noch aus.

**Comment by Telekatz** [comment]
Du hast ein Problem beim Anschluss deines HM-600 an die Batterie. Die Beiden Kanäle liefern nicht die gleiche Leistung. Die Minus Leitungen vom Inverter zur Batterie müssen exakt gleich lang sein, sonst fließt der Strom nicht symmetrisch in beiden Kanälen und die Regelung passt dann nicht mehr.

**Comment by gerd-git** [comment]
Richtig, die einen sind 40cm länger. Ändere ich sofort.....

**Comment by gerd-git** [comment]
In der Tat:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/09a25243-b2f8-4311-a195-3291b80cb8f9)
Jetzt passt auch die Nulleinspeisung:
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/84a4f204-2286-41b8-9862-cb897bdcb5e2)
![grafik](https://github.com/Telekatz/venus.dbus-hoymiles/assets/58742366/a4f4e35e-b0f6-4e18-8614-6506f29fb685)

Ich bin mir noch nicht sicher, wo die Vor- und Nachteile der drei Varianten sind. 
Kann ich das auf "Venus OS" stehen lassen? Ist ESS immer vorhanden, auch wenn der Multiplus nicht mehr da ist?

**Comment by gerd-git** [comment]
Und leider gibt es auch bei Feed-In Mode kein "OFF". Ich würde gerne via NodeRed + MQTT das Limit selber regeln.... Oder übersehe ich da was?

**Comment by Telekatz** [comment]
> Kann ich das auf "Venus OS" stehen lassen? Ist ESS immer vorhanden, auch wenn der Multiplus nicht mehr da ist?

Beim Mode `Venus OS` kommt die Regelung von Venus OS und nicht vom Script wie bei `Grid Target`. Beide regeln den Netzbezug auf den `Sollwert Netz` aus. Dass ESS auch mit dem HM verfügbar ist, ist Ziel diese Scripts.

Die externe Regelung der Leistung ist eine noch offene Baustelle [https://github.com/Telekatz/venus.dbus-hoymiles/issues/4](https://github.com/Telekatz/venus.dbus-hoymiles/issues/4)

**Comment by Head** [comment]
@gerd-git man könnte aber auch ohne die offene Baustelle im Venus OS mode selbst regeln über den Grid setpoint im Venus Node-Red. Ich hatte hier mal angefangen und mir dann einen memory leak mit einer NodeRed Addier-Lib eingefangen und musste mein ganzes Venus OS neu aufsetzen. Seit dem keine Muße mehr.

**Comment by gerd-git** [comment]
Danke Zusammen. Ich hab das Skript jedoch wieder deinstalliert. Die Regelung ist leider zu langsam um den Multiplus komplett, also auch Tagsüber, ersetzen zu können.

Ansich ist der Multiplus ja genau das was man so braucht. Wenn er nicht so Brummen würde. Nachts abschalten via Node-Red ja ist kein Problem. Ebenso das ersatzweise Einschalten meiner Hoymiles, sogar mit einem einfachen für die Nacht ausreichenden Nulleinspeisungsalogritmus (Limit +-5% bei Abweichung von Null alle 15 Sekunden). Wäre für mich Ideal, wenn das VRM bei ausgeschalteten Multiplus weiter den Grid-Verbauch zählen würde, macht es aber nicht. Deswegen versuchte ich das hier. 

Ich bin nun aber an einen Punkt angekommen, wo mir der Fehler im VRM egal ist. Schließlich ist nur das bedeutend, was auf dem Netzbetreiberzähler am Ende das Jahres steht.

Nochmal Danke für Eure Unterstützung.
