### ISSUE TITLE
Support for HMS/Three-Phase-Inverters?

### ISSUE THREAD

**Issue by LukasSchulz** [Telekatz/venus.dbus-hoymiles#13]
Ich habe etwas durch den Code geschaut und habe dort leider nur Support für (mehrere) einphasige Inverter gefunden. Ich plane gerade ein neues System und stehe aktuell vor der Entscheidung, mehrere einphasige oder einen dreiphasigen Inverter zu besorgen. Ist da aktuell support für geplant oder generell nicht? (Ich habe mich leider noch zu wenig damit auseinandergesetzt, ob der limit-mode bei den HMS-Invertern auch für jede Phase einzeln oder nur global geht.)

Danke schonmal für dieses coole Projekt! Falls dreiphasig nicht geplant ist, werde ich einfach einphasige verwenden, ist kein Problem!

**Comment by Telekatz** [comment]
Die integration des HMT (HMS ist einphasig) scheitert momentan noch daran, dass OpenDTU aktuell keine Leistungsdaten für alle drei Phasen ausgibt.

Wobei der HMT meiner Meinung nach trotzdem funktionieren müsst, wenn man ein externes Powermeter für den Inverter verwendet. Damit lässt sich der Inverter auch schneller regeln.
