### ISSUE TITLE
Feed-in PowerLimit will set to 30W, therefore no regulation

### ISSUE THREAD

**Issue by MrBig197x** [Telekatz/venus.dbus-hoymiles#14]
[venus.dbus-hoymiles](https://github.com/Telekatz/venus.dbus-hoymiles)

HM1500 with openDTU is integrated
All settings in the Victron Cerbo are made
Maximum Power Inverter is set to 700W
MQTT Settings are made
Feed in Power Mode is set to VENUS OS
Tasmota as Grid is installed
ESS is konfigured-
The Problem:
With these settings, the Feed-in Power Limit will be set to 30W or 32W?

**Comment by MrBig197x** [comment]
With these settings, the Feed-in Power Limit will be set to max 30W or 32W?

**Comment by MrBig197x** [comment]
However, I have another problem with the integration of the Tasmota smart mete (henne49/dbus-opendtu)r. The values are not transmitted reliably, the connection drops. Unfortunately, this is not the way to use it.

**Comment by Telekatz** [comment]
What are your settings for HM and ESS? Does Venus OS shows the correct power from your grid meter?

**Comment by MrBig197x** [comment]
Hey, Tasmota is integrated and the values are okay

![Victron_HM1500_Device_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/7f7cc93e-aede-44a1-a208-34b3a79e9002)

![Victron_HM1500_Setup](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/320cc711-d82d-496c-80a0-022a5e27679d)
![Victron_HM1500_Setup_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/bb7fbdb6-5e8d-49cc-8868-77025f225e17)
![Victron_HM1500_Setup_3](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/8d5182f6-dbe9-458d-9bc6-249b22b57700)
![VictronDeviceList](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/6d54a93d-cb95-4904-b192-83c849544723)
![Victron_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/7f9f8878-7d5a-430a-838a-103e5966dffd)
![Victron_ESS_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/fc020f8f-1c7b-403a-929c-e2cd36e3f738)
![Victron_ESS_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/c49062e4-abc3-49fe-bb21-d50a09d95c7f)
![Victron_ESS_3](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/e7d6a571-8061-4b83-9192-9682682dd70b)
![Victron_ESS_4](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/555ba70c-3d76-4ca0-b698-8f1df970c1ed)
![Victron_HM1500_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/586adf29-77f2-4fcd-abb9-860ff2fbaed1)
![Victron_HM1500_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/817a253e-a1c3-4450-a1d1-93ea5dc475f9)
![Victron_HM1500_Device](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/55833397-23e0-437d-be83-42152e1a549a)

**Comment by MrBig197x** [comment]
Hey, Tasmota is integrated and the Values are okay. Intervall 2 seconds.
![Victron_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/e2c1b788-b013-49b9-abc0-e0f202a1fac8)
![Victron_ESS_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/8ca03e2a-c617-411d-87d7-e01bf9604d99)
![Victron_ESS_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/475df8ef-0303-4066-8e9c-8e16f99b588c)
![Victron_ESS_3](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/54ba5357-fbc3-4cd7-b57a-328a1b0c2a3d)
![Victron_ESS_4](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/99e9b341-4dec-4c39-94cd-6e2588c488d1)
![Victron_HM1500_1](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/078b8d18-ce24-4572-bf22-fbfac2477272)
![Victron_HM1500_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/ddc30edc-8ba6-4316-a5c3-0aaf1db1bd9b)
![Victron_HM1500_Device](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/995209e0-6443-45d9-a9ab-1d04a4da74df)
![Victron_HM1500_Device_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/ea1095f8-7d60-4900-9af4-4902f5b54e70)
![Victron_HM1500_Setup](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/eb7fce28-4cfb-4bfb-8013-abccb03d759d)
![Victron_HM1500_Setup_2](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/223c6950-441d-4be5-b35d-89ccd21b49a5)
![Victron_HM1500_Setup_3](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/9ba64736-6b9b-4ebf-9257-c5caeed35e08)
![VictronDeviceList](https://github.com/Telekatz/venus.dbus-hoymiles/assets/139586714/60340f42-5c17-4c47-8429-f66ed767fec9)

**Comment by Head** [comment]
Mach mal `Optimiert (ohne BatteryLife)`, "mit" hatte bei mir auch zu seltsamen Verhalten geführt.

**Comment by Telekatz** [comment]
Die Integration deines Grid Meters sieht unvollständig aus. Kein Strom, keine Spannung und nur eine Phase.

**Comment by MrBig197x** [comment]
Ich bekomme nur den Total Verbrauch, die aktuelle Wirkleistung saldiert und die aktuelle Wirkleistung L1, L2 und L3 übertragen, Strom und Spannung leider nicht.

**Comment by Telekatz** [comment]
In deinem VRM Screenshot steht aber nur die L1 Leistung vom Grid Meter.

Stehen in der log Datei im Scriptverzeichniss irgendwelche Fehlermeldungen?

**Comment by MrBig197x** [comment]
Muss ich mir heute Abend anschauen, ich melde mich. Vielen Dank für den bisherigen Support

**Comment by MrBig197x** [comment]
Hallo,
die Integration scheint des Tasmota scheint tatsächlich nicht richtig zu sein.
Allerdings kann ich mich nicht mehr per Putty bzw. WINSCP auf den Cerbo aufschalten.
Ich bekomme trotz gesetztem Superuser und Passwort den Zugriff verweigert?
Keine Ahnung warum.
Per Kommandozeile ssh root@xxx.xxx.xxx.xx komme ich drauf.

**Comment by MrBig197x** [comment]
Hallo, 
kurze Rückmeldung. 
Das Problem ist gelöst und es war die Tasmota Integration. 
Ich habe den Tasmota über das Projekt venus.dbus-tasmota-smartmeter integriert. 
Vielen Dank für die Hilfe.
