### ISSUE TITLE
Second Inverter is always disabled

### ISSUE THREAD

**Issue by MrWh1t3-h-brs** [Telekatz/venus.dbus-hoymiles#18]
I have enabled a second hoymiles inverter in the config.ini (both inverters connected through one OpenDTU). I can see him inside VenusOS and can change his settings. I can see his values too. But unfortunatelly the second inverter receives always the command to shut down from Venus OS although he is enabled in my settings. Even if I restart him manually, a few minutes later he receives a command from Venus OS to shut down. Is that a bug or have I done something wrong?
Thx

**Comment by Telekatz** [comment]
Is the startup limit function activated?

**Comment by MrWh1t3-h-brs** [comment]
Thanks so far for providing your solution! It fits very well to my needs.

No,
it is deactivated. I provide some pictures maybe it will help.

# Here the both inverters
## Inside Venus OS:
![Bildschirmfoto 2024-02-29 um 08 18 43](https://github.com/Telekatz/venus.dbus-hoymiles/assets/33173542/f35fb446-e3bd-4d79-b6b2-0ad365f8d65e)

## config.ini:
![Bildschirmfoto 2024-02-29 um 08 13 01](https://github.com/Telekatz/venus.dbus-hoymiles/assets/33173542/6186b407-4bf8-49c7-b665-8b9bf3fe6977)

## In OpenDTU:
![Bildschirmfoto 2024-02-29 um 08 16 04](https://github.com/Telekatz/venus.dbus-hoymiles/assets/33173542/b276d212-88a9-44d7-bf88-7e3bc91e8cec)

# HM-800_2 Setup inside Venus OS:
**Enabled:**       true
**Maximum Inverter Power:** 800W (I played a lot with this value)
**Phase:** L1
**MQTT:** (Not importent here, it works)
**DTU:** OpenDTU
**Startup Limit:** false
**Feed-In Limit Mode:** Grid Target
**Grid Target Interval:** 3s
**Grid Target Power:** 50W
**Grid Target Tolerance Minimum:** 30W
**Grid Target Tolerance Maximum:** 40W
**Power Meter:** Internal
**Restart inverter at midnight:** true

# HM-800 Setup inside Venus OS:
**Enabled:** true
**Maximum Inverter Power:** 100W (I played a lot with this value seems not to have any impact)
**Phase:** L1
**MQTT Settings:** (not importent here)
**DTU:** OpenDTU

**Comment by Telekatz** [comment]
Can you provide a log with Logging=DEBUG where I can see the shut down of the second inverter.

**Comment by MrWh1t3-h-brs** [comment]
I could now solve it for me localy by adding the command 
`self._active = True`
into HMpvinverter.py between lines 328 and 329.
