### ISSUE TITLE
(PR) Allow external control of HM

### ISSUE THREAD

**Issue by ude6** [Telekatz/venus.dbus-hoymiles#4]
Dear Telekatz,
thank you for this great project. I am using a similar setup as yours but use Node-Red for the control 
of the HM via Open-DTU. Would it be possible to implement another "limit Mode" that would disable the 
steering of the HM via your driver and only leave the display of the values in the cerbo?

Thanks
Andreas

**Comment by Telekatz** [comment]
Would a limit mode help you, where you can specify a limit externally via the dbus?

**Comment by ude6** [comment]
I guess that would also do the trick. I could then post to the dbus from Node-Red instead 
of going directly to MQTT-->Open-DTU...

**Comment by TheGrumpyBadger** [comment]
Yes, that would be very handy. Thx.

**Comment by Telekatz** [comment]
I created a new branch to test this feature.
After selecting the "External" feed-in limit mode, the limit can now be set by writing the value to the path "/Ac/PowerLimit" of the dbus service "com.victronenergy.hm".

**Comment by ude6** [comment]
That was quick :-) 
I have to set-up a Raspi to test this. Can not take "production" down and risk the running system.
I will need a few days :-(

**Comment by TheGrumpyBadger** [comment]
Is this "external" branch based on VenusOS v2.9 or already for v3.00 ?

**Comment by Telekatz** [comment]
The External_control branch is for V2.92.
