### ISSUE TITLE
AC Phase L1 empty and "Power Meter: Unknown"

### ISSUE THREAD

**Issue by Head** [Telekatz/venus.dbus-hoymiles#6]
Hi,

I'm using https://github.com/mr-manuel/venus-os_dbus-mqtt-grid to feed in my Power Meter data and the Venus Home screen shows Grid and AC Loads as expected. But your script shows "Power Meter: Unknown" and no data in the "AC Phase Lx" section.

I've also created an issue in the dbus-mqtt-grid project: https://github.com/mr-manuel/venus-os_dbus-mqtt-grid/issues/1 not knowing which script is missing something?

**Comment by Telekatz** [comment]
The "Power Meter" setting is for an optional additional power meter that measures the power of the inverter. An external power meter makes shorter control intervals possible than with the values from the inverter.

The fact that you don't have a reading in the "AC Phase Lx" section has nothing to do with the "Power meter" setting, as this section always shows the reading of the inverter. If you don't have any values here, then something is probably wrong with the MQTT or DTU settings.
